#!/bin/bash -ex

 dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
 }

 VERSION="master.zip"
 URL="https://github.com/slims/slims8_akasia/archive/$VERSION"

 dl $URL /usr/local/src

