#!/bin/sh -ex

DB_NAME=senayandb
DB_USER=senayandb_usr
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/slims8

# unpack SLIMS and tidy up

 unzip $SRC/master.zip -d $SRC
 cp -a $SRC/slims8_akasia-master/. $WEBROOT
 rm -rf $SRC/*

# Make sure root has control of website
chown -R root:root $WEBROOT

# Make sure the web-user can do things in the necessary directories

chown -R www-data:www-data $WEBROOT/images
chown -R www-data:www-data $WEBROOT/config
chown -R www-data:www-data $WEBROOT/files
chown -R www-data:www-data $WEBROOT/repository

# configure apache
a2dissite 000-default
a2ensite slims8
a2enmod rewrite
sed -i 's/memory_limit =.*/memory_limit = 64M/' /etc/php5/apache2/php.ini
sed -i 's/memory_limit =.*/memory_limit = 128M/' /etc/php5/cli/php.ini

# start services
service mysql start
service apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# import the database structure
mysql --user=$DB_USER --password=$DB_PASS senayandb < /var/www/slims8/install/senayan.sql

# create sysconfig.local.inc with the connection settings above
# step 1. create the file from the sample 2. substitute correct settings using sed 

cp /var/www/slims8/config/sysconfig.local.inc-sample.php /var/www/slims8/config/sysconfig.local.inc.php

# step 2. substitute correct settings using sed

sed -i "s/_DB_HOST_/localhost/" /var/www/slims8/config/sysconfig.local.inc.php
sed -i "s/_DB_PORT_/3306/" /var/www/slims8/config/sysconfig.local.inc.php
sed -i "s/_DB_NAME_/senayandb/" /var/www/slims8/config/sysconfig.local.inc.php
sed -i "s/_DB_USER_/senayandb_usr/" /var/www/slims8/config/sysconfig.local.inc.php

# Add Australian English and Burmese to the language menu for this version
# This will APPEND the lines so they are distinguished from the normal distribution by being at the end. 
echo "\$available_languages[] = array('my_MM', __('Myanmar(Burmese)'), 'Myanmar(Burmese)');" >> /var/www/slims8/lib/lang/localisation.php
echo "\$available_languages[] = array('en_AU', __('Australian English'), 'Australian English');" >> /var/www/slims8/lib/lang/localisation.php

# And tidy up the install folder, so the warning message isn't issued to library admin.

mv /var/www/slims8/install /var/www/slims8/for_install

# Note: we leave the folder here so sampledata.sql is still available if wanted

# Try to do the pecl install for yaz 

echo | pecl install yaz

# make yaz available to php

echo "extension=yaz.so" >>/etc/php5/apache2/php.ini

# stop services
service mysql stop
service apache2 stop

