#!/bin/bash -e
# regenerate slims8 db user mysql password

. /etc/default/inithooks

CONF=/var/www/slims8/config/sysconfig.local.inc.php
PASSWORD=$(mcookie)

sed -i "s/_DB_PASSWORD_/${PASSWORD}/" $CONF


$INITHOOKS_PATH/bin/mysqlconf.py --user=senayandb_usr --pass="$PASSWORD"
